### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Hat",
  "price": 100.0,
  "stockQuantity": 2
}

###

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "",
  "price": -100.0,
  "stockQuantity": -2
}

###
GET http://localhost:8080/products

###
GET http://localhost:8080/products/5

###
GET http://localhost:8080/products/99

###
PUT http://localhost:8080/products/5

###
PUT http://localhost:8080/products/6
Content-Type: application/json

{
  "name": "Baby Frock",
  "price": 505.0,
  "stockQuantity": 2
}

###
PUT http://localhost:8080/products/1/name
Content-Type: text/plain

Granny square

###
PUT http://localhost:8080/products/5/name
Content-Type: text/plain

Frock

###
DELETE http://localhost:8080/products/5

